device: 'cpu'
hidden_units: 50
num_blocks: 2
num_heads: 1
dropout_rate: 0.2
maxlen: 200
batch_size: 512
use_conv: False
metrics:
    - popularity
    #- temprature
num_groups: 20
skip_threshold: 1

lora:
  num_epochs: 15
  lr: 5e-4
  weight_decay: 1e-2
  lora_rank : 1
  lora_alpha: 64
  target_modules:
    - attention_layers.0
    - attention_layers.1
  # target_modules:
  #   - forward_layers.0.linear1
  #   - forward_layers.0.linear2
  #   - forward_layers.1.linear1
  #   - forward_layers.1.linear2

moe:
  num_epochs: 5
  lr: 1e-2
  weight_decay: 1e-2
  gamma: 0.5


ensemble:
  alpha:
    - 0.5
    - 0.5