device: 'cuda'
hidden_units: 64
num_blocks: 2
num_heads: 4
dropout_rate: 0.2
maxlen: 200
batch_size: 512
use_conv: False
metrics:
    - popularity
    - temprature
num_groups: 32
skip_threshold: 0.18

lora:
  num_epochs: 16
  lr: 5e-4
  weight_decay: 1e-2
  lora_rank : 64
  lora_alpha: 8
  target_modules:
    - attention_layers.0
    - attention_layers.1

moe:
  num_epochs: 16
  lr: 1e-3
  weight_decay: 1e-2
  gate_linear_config : 12800

ensemble:
  alpha:
    - 0.9
    - 0.1
  maxlen: 200